### ISSUE TITLE
Version conflict on git2

### ISSUE THREAD

**Issue by martinellison** [davidB/git2_credentials#7]
There seems to be a version conflict on git2: git2_credentials is requiring version 0.10, but the latest version of git2 is 0.11. 

What I am getting is:
> error: failed to select a version for `libgit2-sys`.
>     ... required by package `git2 v0.10.0`
>     ... which is depended on by `git2_credentials v0.3.2`
>     ... which is depended on by [my code]
[etc]
> versions that meet the requirements `^0.9.0` are: 0.9.2, 0.9.1, 0.9.0
> 
> the package `libgit2-sys` links to the native library `git2`, but it conflicts with a previous package which links to `git2` as well:
> package `libgit2-sys v0.10.0`
>     ... which is depended on by `git2 v0.11.0`
>     ... which is depended on by [my code, same as above]
[etc]

**Comment by davidB** [comment]
I just published the version 0.4.0 with git2 0.11 as dependencies (I received the dependabot PR this morning).

Thanks for the notification.
