### ISSUE TITLE
Not working with local SSH keys

### ISSUE THREAD

**Issue by cecton** [davidB/git2_credentials#9]
First thank you for your work!

I have tried this crate today and I found out that it is using the SSH agent. So I killed the daemon :smiling_imp: and try again and now it says: `error authenticating: failed connecting with agent; class=Ssh (23)`

I have the impression that this crate doesn't handle at all the id_rsa and id_rsa.pub in the `$HOME/.ssh`

Is it supported? Do you intend to support it? (Do you want a PR?)

**Comment by davidB** [comment]
Hi,

Thanks for the feedback. you are right it doesn't handle well all the key (id_rsa, id_ed25519 or any name).

PR are welcome.

You can start at https://github.com/davidB/git2_credentials/blob/master/src/lib.rs#L163

**Comment by cecton** [comment]
Thank you for the release :grin:
